# Don't change these unless you really understand what you are doing with them.
other_parameters = dict(model_filename='../model/model.pth',
                        box_dimensions=[6, 6, 6],
                        box_overlap=[0.5, 0.5, 0.5],
                        min_points_per_box=1000,
                        max_points_per_box=20000,
                        noise_class=0,
                        terrain_class=1,
                        vegetation_class=2,
                        cwd_class=3,
                        stem_class=4,
                        grid_resolution=0.5,
                        supplementary_map_resolution=0.1,
                        num_neighbours=5,
                        Vegetation_coverage_resolution=1.0,
                        sorting_search_angle=20,
                        sorting_search_radius=1,
                        sorting_angle_tolerance=90,
                        max_search_radius=3,
                        max_search_angle=30)
